import 'package:hive/hive.dart';

import '../core/database/hive_boxes.dart';

const String _kSkippedQuestTitles = 'skipped_quest_titles';

/// Remembers which suggested quests the user has dismissed.
///
/// This used to be a `Set<String>` held in the Quests screen's State, so every
/// skip was forgotten on restart and dismissed suggestions came straight back —
/// which reads as the app ignoring the user.
///
/// Keyed on title rather than id because candidates are regenerated by the rule
/// engine on every build and never persisted, so they have no stable id. Titles
/// are templated from category and duration, so they're stable for as long as
/// the underlying suggestion is.
class SkippedQuestRepository {
  Box<dynamic> get _box => Hive.box<dynamic>(HiveBoxes.appState);

  Set<String> get titles {
    final stored = _box.get(_kSkippedQuestTitles);
    if (stored is! List) return <String>{};
    return stored.cast<String>().toSet();
  }

  Future<void> skip(String title) async {
    await _box.put(_kSkippedQuestTitles, {...titles, title}.toList());
  }

  /// Lets a user undo a skip, and keeps the list from growing forever as the
  /// rule engine's templates change.
  Future<void> unskip(String title) async {
    await _box.put(
      _kSkippedQuestTitles,
      titles.where((t) => t != title).toList(),
    );
  }

  Future<void> clear() => _box.delete(_kSkippedQuestTitles);

  /// Overwrites the whole set — the JSON backup restore's write path,
  /// which has a complete replacement set rather than one title to add.
  Future<void> replaceAll(Set<String> titles) =>
      _box.put(_kSkippedQuestTitles, titles.toList());
}
