/// Pure date math for [RecurringTransaction] materialization — no Flutter,
/// Hive box, or uuid dependency, same reasoning as xp_engine.dart and
/// quest_engine.dart: independently unit-testable, and the one place this
/// logic lives.
///
/// Deliberately hands back occurrence *dates*, not [Transaction]s — the
/// caller (the repository) owns id generation and persistence, matching how
/// quest_template_engine.dart hands back a `QuestCandidate` rather than a
/// fully-formed `Quest`.
library;

import '../../models/recurring_transaction.dart';

/// Safety cap on occurrences generated by a single [materializeOccurrences]
/// call. A rule that's sat dormant for a long time (the app not opened in
/// months, a daily rule anchored years ago) shouldn't flood the transaction
/// list on the next launch — only the most recent occurrences are
/// generated; the cursor still advances past everything older, so nothing
/// is generated twice on a later pass.
const int kMaxCatchUpOccurrences = 90;

class MaterializationResult {
  const MaterializationResult({
    required this.dueDates,
    required this.nextDueDate,
  });

  /// Dates a transaction should be created for, oldest first. Capped at
  /// [kMaxCatchUpOccurrences] regardless of how far the backlog actually goes.
  final List<DateTime> dueDates;

  /// Where the rule's cursor should be saved to after this pass — always
  /// past every occurrence that was due, even ones silently dropped by the
  /// cap above.
  final DateTime nextDueDate;
}

/// Given where a recurring rule's cursor ([nextDueDate]) currently sits,
/// returns every occurrence due at or before [now] (and at or before
/// [endDate], if the rule has one) and the cursor's new position.
MaterializationResult materializeOccurrences({
  required DateTime nextDueDate,
  required RecurrenceFrequency frequency,
  required DateTime now,
  DateTime? endDate,
}) {
  final cutoff = (endDate != null && endDate.isBefore(now)) ? endDate : now;

  final allDue = <DateTime>[];
  var due = nextDueDate;
  while (!due.isAfter(cutoff)) {
    allDue.add(due);
    due = _advance(due, frequency);
  }

  final capped = allDue.length > kMaxCatchUpOccurrences
      ? allDue.sublist(allDue.length - kMaxCatchUpOccurrences)
      : allDue;

  return MaterializationResult(dueDates: capped, nextDueDate: due);
}

/// Occurrence dates a rule will produce within [rangeStart, rangeEnd]
/// inclusive — the forward-looking counterpart to [materializeOccurrences],
/// used to forecast upcoming commitments (e.g. Insights' "left to pay this
/// month") rather than to generate past-due transactions. Pure: doesn't
/// touch [nextDueDate] or persist anything.
List<DateTime> forecastOccurrences({
  required DateTime nextDueDate,
  required RecurrenceFrequency frequency,
  required DateTime rangeStart,
  required DateTime rangeEnd,
  DateTime? endDate,
}) {
  final cutoff = (endDate != null && endDate.isBefore(rangeEnd))
      ? endDate
      : rangeEnd;

  var due = nextDueDate;
  // Defensive: nextDueDate should already be at or past rangeStart (the
  // repository advances it on every materialize pass), but skip forward
  // rather than assume it.
  while (due.isBefore(rangeStart)) {
    due = _advance(due, frequency);
  }

  final result = <DateTime>[];
  while (!due.isAfter(cutoff)) {
    result.add(due);
    due = _advance(due, frequency);
  }
  return result;
}

DateTime _advance(DateTime date, RecurrenceFrequency frequency) {
  return switch (frequency) {
    RecurrenceFrequency.daily => date.add(const Duration(days: 1)),
    RecurrenceFrequency.weekly => date.add(const Duration(days: 7)),
    // DateTime normalizes both month overflow (month 13 rolls into next
    // January) and day overflow (Jan 31 + 1 month has no Feb 31, so it
    // rolls into early March) — a rule anchored on the 29th-31st drifts
    // across short months. Accepted as a pragmatic simplification rather
    // than clamping to each month's actual last day.
    RecurrenceFrequency.monthly => DateTime(
      date.year,
      date.month + 1,
      date.day,
    ),
  };
}
